### ISSUE TITLE
NULL Safety

### ISSUE THREAD

**Issue by ManmohanTalwar** [roughike/streaming_shared_preferences#17]
Hello, I have recently migrated my project to Null Safety, and it this package is contradicting in migrating it. Kindly migrate it to null Safety.

**Comment by JonasWanke** [comment]
There's already an open PR for that: #16. Until that gets merged and published, you can try it out by specifying the following in your `pubspec.yaml`:

```yaml
dependencies:
  # Other dependencies…
  streaming_shared_preferences:
    git:
      url: https://github.com/roughike/streaming_shared_preferences
      ref: a460743730d4653176455747362579a76f542e18
```
